spring:
  # 默认的profile为dev，其他环境通过指定启动参数使用不同的profile，比如：
  #   测试环境：java -jar my-spring-boot.jar --spring.profiles.active=test
  #   生产环境：java -jar my-spring-boot.jar --spring.profiles.active=prod
  profiles:
    active: dev
logging:
  level:
    root: info
